train:
  _target_: src.datasets.AVDataset
  dataset_name: example
  name: cv
  audio_path: audio
  video_path: mouth
  text_path: text
  n_src: 1
  distillation: True
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.AVDataset
  dataset_name: example
  name: cv
  audio_path: audio
  video_path: mouth
  text_path: text
  n_src: 1
  distillation: True
  instance_transforms: ${transforms.instance_transforms.inference}
