_target_: src.model.CTCNetModel
# sample_rate: 16000
# filterbank
n_filters: 512
kernel_size: 21
stride: 20 # as student
# masknet
n_src: 1
n_blocks: 8
an_repeats: 3
fn_repeats: 3 # as student
mask_act: relu
act_type: prelu
norm_type: gLN
bn_chan: 256 # as student
hid_chan: 256 # as student
# video
vin_chan: 256 # as student
vout_chan: 512 # 1024 as student, even more than before
vconv_kernel_size: 3
vn_repeats: 3 # as student, does not change anything?
# fusion
fout_chan: 256 # as student
# video frcnn
video_config:
  in_chan: 64
  out_chan: 64
  depth: 4
  iter: 3
  shared: True # in original config it is false
  norm_type: "BatchNorm1d"
  act_type: "prelu"
  kernel_size: 3
video_model:
  _target_: src.model.video.VideoModel
  backbone_type: resnet
  relu_type: prelu
  width_mult: 1.0
  pretrain: frcnn_128_512.backbone.pth.tar
train_video_model: false
asr_model_name: ASRExample
asr_model_config:
  n_input_feats: 1640
  n_audio_feats: 32000
  fc_hidden: 512
