_target_: src.model.CTCNetModel
# sample_rate: 16000
# filterbank
n_filters: 512
kernel_size: 21
stride: 20 # as student
# masknet
n_src: 1
n_blocks: 8
an_repeats: 3
fn_repeats: 3 # as student
mask_act: relu
act_type: prelu
norm_type: gLN
bn_chan: 256 # as student
hid_chan: 256 # as student
# video
vin_chan: 256 # as student
vout_chan: 1024 # 1024 as student, even more than before
vconv_kernel_size: 3
vn_repeats: 3 # as student, does not change anything?
# fusion
fout_chan: 256 # as student
# video frcnn
video_config:
  in_chan: 64
  out_chan: 64
  depth: 4
  iter: 3
  shared: True # in original config it is false
  norm_type: "BatchNorm1d"
  act_type: "prelu"
  kernel_size: 3
video_model:
  _target_: src.model.video.VideoModel
  backbone_type: shufflenet
  relu_type: prelu
  width_mult: 0.5
  pretrain: lrw_snv05x_tcn1x.pth.tar
train_video_model: false
asr_model_name: ASRConformer
asr_model_config:
  input_dim: 256
  num_encoder_layers: 1
  res_reduce: 125
  conv_kernel_size: 7
  encoder_dim: 64
  do_subsample: false
