_target_: src.model.AVSSRModel
ss_model:
  _target_: src.model.ctcnet.CTCNet
  # sample_rate: 16000
  # filterbank
  n_filters: 512
  kernel_size: 21
  stride: 10
  # masknet
  n_src: 1
  n_blocks: 8
  an_repeats: 3
  fn_repeats: 3 # as student
  mask_act: relu
  act_type: prelu
  norm_type: gLN
  bn_chan: 256 # as student
  hid_chan: 256 # as student
  # video
  vin_chan: 256 # as student
  vout_chan: 512 # 1024 as student, even more than before (because n_src=2)
  vconv_kernel_size: 3
  vn_repeats: 3 # as student, does not change anything?
  # fusion
  fout_chan: 256 # as student
  # video frcnn
  video_config:
    in_chan: 64
    out_chan: 64
    depth: 4
    iter: 3
    shared: True # in original config it is false
    norm_type: "BatchNorm1d"
    act_type: "prelu"
    kernel_size: 3
video_model:
  _target_: src.model.video.VideoModel
  backbone_type: resnet
  relu_type: prelu
  width_mult: 1.0
  pretrain: frcnn_128_512.backbone.pth.tar
train_video_model: false
asr_model:
  _target_: src.model.asr.ASRExample
  n_input_feats: 16
  n_hidden_channels: 32
  res_reduce: 313
  input_channels: 1
  n_repeats: 4
