_target_: src.model.AVSSRModel
ss_model:
  _target_: src.model.rtfsnet.RTFSNet
  n_src: 1
  pretrained_vout_chan: 512  # output from pretrained model

  video_bn_params:
    kernel_size: -1

  audio_bn_params:
    pre_norm_type: gLN
    pre_act_type: ReLU
    out_chan: 256
    kernel_size: 1
    is2d: true

  enc_dec_params:
    encoder_type: STFTEncoder
    decoder_type: STFTDecoder
    win: 256
    hop_length: 128
    out_chan: 256
    kernel_size: 3
    stride: 1
    bias: false
    act_type:
    norm_type:

  audio_params:
    audio_net: TDANet
    # in_chan same as audio_bn_chan
    hid_chan: 64
    kernel_size: 4
    stride: 2
    norm_type: gLN
    act_type: PReLU
    upsampling_depth: 2
    repeats: 4
    shared: true
    is2d: true
    layers:
      layer_1:
        layer_type: DualPathRNN
        hid_chan: 32
        dim: 4
        kernel_size: 8
        stride: 1
        rnn_type: SRU
        num_layers: 4
        bidirectional: true
      layer_2:
        layer_type: DualPathRNN
        hid_chan: 32
        dim: 3
        kernel_size: 8
        stride: 1
        rnn_type: SRU
        num_layers: 4
        bidirectional: true
      layer_3:
        layer_type: MultiHeadSelfAttention2D
        dim: 3
        n_freqs: 64
        n_head: 4
        hid_chan: 4
        act_type: PReLU
        norm_type: LayerNormalization4D

  video_params:
    video_net: TDANet
    # in_chan same as video_bn_chan
    hid_chan: 64
    kernel_size: 3
    stride: 2
    norm_type: BatchNorm1d
    act_type: PReLU
    upsampling_depth: 4
    repeats: 1
    shared: true
    is2d: false
    layers:
      layer_1:
        layer_type: GlobalAttention
        ffn_name: FeedForwardNetwork
        kernel_size: 3
        n_head: 8
        dropout: 0.1

  fusion_params:
    fusion_type: ATTNFusion
    fusion_shared: true
    kernel_size: 4
    is2d: true

  mask_generation_params:
    mask_generator_type: MaskGenerator
    mask_act: ReLU
    RI_split: true
    is2d: true

video_model:
  _target_: src.model.video.VideoModel
  backbone_type: resnet
  relu_type: prelu
  width_mult: 1.0
  pretrain: frcnn_128_512.backbone.pth.tar
train_video_model: false
asr_model:
  _target_: src.model.asr.ASRRNN
  rnn_input_size: 129
  rnn_hidden_size: 32
  rnn_bidirectional: True
  rnn_num_layers: 1
  res_reduce: 500
  input_channels: 256
