defaults:
  - model: rtfsnet4_small_nemo_video
  - datasets: lrs2 #lrs2_test_only
  - dataloader: main
  - transforms: main
  - quantization: main
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  #use_lm: True #False
  #use_lm_small: True #False
  nemo_model: "stt_en_conformer_ctc_small"
  beam_size: 100


inferencer:
  device_tensors: ["mix_audio", "s_audio", "s_video", "s_tokens_length", "s_audio_length"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  quantization: False
  SS_targets: True
  load_path: "lrs2_SS"
  override: False # if True, will override the previous run with the same name
  save_path: "lrs2" # use dataset name
  seed: 1
  # include from_pretrained