checkpoint_path: 'data/pretrain/quantized/quantized_model_dynamic.pth' 
dynamic_modules: 
- encoder.layers.0.feed_forward1

- encoder.layers.0.self_attn
- encoder.layers.0.feed_forward2
- encoder.layers.1.feed_forward1

- encoder.layers.1.self_attn
- encoder.layers.1.feed_forward2
- encoder.layers.2.feed_forward1

- encoder.layers.2.self_attn
- encoder.layers.2.feed_forward2
- encoder.layers.3.feed_forward1

- encoder.layers.3.self_attn
- encoder.layers.3.feed_forward2
- encoder.layers.4.feed_forward1

- encoder.layers.4.self_attn
- encoder.layers.4.feed_forward2
- encoder.layers.5.feed_forward1

- encoder.layers.5.self_attn
- encoder.layers.5.feed_forward2
- encoder.layers.6.feed_forward1

- encoder.layers.6.self_attn
- encoder.layers.6.feed_forward2
- encoder.layers.7.feed_forward1

- encoder.layers.7.self_attn
- encoder.layers.7.feed_forward2
- encoder.layers.8.feed_forward1

- encoder.layers.8.self_attn
- encoder.layers.8.feed_forward2
- encoder.layers.9.feed_forward1

- encoder.layers.9.self_attn
- encoder.layers.9.feed_forward2
- encoder.layers.10.feed_forward1

- encoder.layers.10.self_attn
- encoder.layers.10.feed_forward2
- encoder.layers.11.feed_forward1

- encoder.layers.11.self_attn
- encoder.layers.11.feed_forward2
- encoder.layers.12.feed_forward1

- encoder.layers.12.self_attn
- encoder.layers.12.feed_forward2
- encoder.layers.13.feed_forward1

- encoder.layers.13.self_attn
- encoder.layers.13.feed_forward2
- encoder.layers.14.feed_forward1

- encoder.layers.14.self_attn
- encoder.layers.14.feed_forward2
- encoder.layers.15.feed_forward1

- encoder.layers.15.self_attn
- encoder.layers.15.feed_forward2

static_modules: []
#- encoder.pre_encode

