checkpoint_path: 'data/pretrain/quantized/custom_config_hist_eq_channelwise_0.9999_HS.pth' 
dynamic_modules: []
static_modules:
#- encoder.pre_encode
- encoder.layers.0.feed_forward1
- encoder.layers.0.conv
- encoder.layers.0.self_attn
- encoder.layers.0.feed_forward2
- encoder.layers.1.feed_forward1
- encoder.layers.1.conv
- encoder.layers.1.self_attn
- encoder.layers.1.feed_forward2
- encoder.layers.2.feed_forward1
- encoder.layers.2.conv
- encoder.layers.2.self_attn
- encoder.layers.2.feed_forward2
- encoder.layers.3.feed_forward1
- encoder.layers.3.conv
- encoder.layers.3.self_attn
- encoder.layers.3.feed_forward2
- encoder.layers.4.feed_forward1
- encoder.layers.4.conv
- encoder.layers.4.self_attn
- encoder.layers.4.feed_forward2
- encoder.layers.5.feed_forward1
- encoder.layers.5.conv
- encoder.layers.5.self_attn
- encoder.layers.5.feed_forward2
- encoder.layers.6.feed_forward1
- encoder.layers.6.conv
- encoder.layers.6.self_attn
- encoder.layers.6.feed_forward2
- encoder.layers.7.feed_forward1
- encoder.layers.7.conv
- encoder.layers.7.self_attn
- encoder.layers.7.feed_forward2
- encoder.layers.8.feed_forward1
- encoder.layers.8.conv
- encoder.layers.8.self_attn
- encoder.layers.8.feed_forward2
- encoder.layers.9.feed_forward1
- encoder.layers.9.conv
- encoder.layers.9.self_attn
- encoder.layers.9.feed_forward2
- encoder.layers.10.feed_forward1
- encoder.layers.10.conv
- encoder.layers.10.self_attn
- encoder.layers.10.feed_forward2
- encoder.layers.11.feed_forward1
- encoder.layers.11.conv
- encoder.layers.11.self_attn
- encoder.layers.11.feed_forward2
- encoder.layers.12.feed_forward1
- encoder.layers.12.conv
- encoder.layers.12.self_attn
- encoder.layers.12.feed_forward2
- encoder.layers.13.feed_forward1
- encoder.layers.13.conv
- encoder.layers.13.self_attn
- encoder.layers.13.feed_forward2
- encoder.layers.14.feed_forward1
- encoder.layers.14.conv
- encoder.layers.14.self_attn
- encoder.layers.14.feed_forward2
- encoder.layers.15.feed_forward1
- encoder.layers.15.conv
- encoder.layers.15.self_attn
- encoder.layers.15.feed_forward2
